### ISSUE TITLE
메인 UI 기획

### ISSUE THREAD

**Issue by soyagok11** [teamcrossback/DoubleDuel#3]
오늘 회의했던 내용에 따라 우선 러프하게 기획

**Comment by dbstn003** [comment]
방으로 이루어진 회전문 UI를 생각했던 것이었으나
이게 과연 세계관과 일치할 지 의문

예를 들어 큐라레의 경우에는 게임 설정의 중심지인 도서관을 3d로 표현했음
우리도 게임 설정의 중심지(플레이어들이 소환배틀을 하는 그런 특별한 장소(?) )
를 생각해 봐야 할 것 같음

그리고 대전/덱/상점/커뮤니티 방으로 하는 것과
메인 UI가 있고 거기서부터 대전/덱/상점/커뮤니티 방으로 가는 방식 중에
어느 것이 나을 지

**Comment by soyagok11** [comment]
아이갓디스

다음주 월요일즈음에 의논해봅시다

**Comment by soyagok11** [comment]
대충 틀은 잡힘

문서화할 필요가 있음
